/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define AHB1_ENR_ADDR					(0x40023800UL + 0x30UL)
#define APB2_ENR_ADDR					(0x40023800UL + 0x44UL)
#define GPIO_MODER_ADDR					0x40020C00UL
#define GPIO_ODR_ADDR					0x40020C14UL
#define GPIO_PORT_NUM					3
#define GPIO_PIN_NUM_INPUT				11
#define GPIO_INPUT_PIN_MODE				0x0
#define GPIO_PIN_NUM_OUTPUT				9
#define GPIO_OUTPUT_PIN_MODE			0x1
#define NVIC_ISER_ADDR					0xE000E104UL
#define BUTTON_IRQ_NO					40
#define SYSCFG_EXTI_CR_ADDR				(0x40013800UL + 0x10UL)
#define EXTI_IMR_ADDR					0x40013C00UL
#define EXTI_PR_ADDR					(0x40013C00UL + 0x14UL)
#define EXTI_RTSR_ADDR					(0x40013C00UL + 0x08UL)
#define EXTI_FTSR_ADDR					(0x40013C00UL + 0x0CUL)
#define EXTI_INTERRUPT_PIN_NUM			11
#define SLEEP_COUNT						500000
#define ENABLE							1

void delay(void)
{
	uint32_t j;
	for(j=0;j<SLEEP_COUNT;j++);
}

void EXTI15_10_IRQHandler(void)
{
	uint32_t *pGPIO_ODR = (uint32_t *) GPIO_ODR_ADDR;
	uint32_t current_value;
	uint32_t *pEXTI_PR = (uint32_t *) EXTI_PR_ADDR;

	// Toggling the LED
	current_value = ((*pGPIO_ODR >> GPIO_PIN_NUM_OUTPUT) & 0x1);
	current_value ^= 0x1;
	*pGPIO_ODR &= ~(1 << GPIO_PIN_NUM_OUTPUT);
	*pGPIO_ODR |= (current_value << GPIO_PIN_NUM_OUTPUT);

	delay(); // For de-bouncing the input button

	// Clearing the EXTI_PR Register
	*pEXTI_PR |= (1 << EXTI_INTERRUPT_PIN_NUM);
}

int main(void)
{

	uint32_t *pAHB1ENR = (uint32_t *) AHB1_ENR_ADDR;
	uint32_t *pAPB2ENR = (uint32_t *) APB2_ENR_ADDR;
	uint32_t *pGPIO_MODER = (uint32_t *) GPIO_MODER_ADDR;
	uint32_t *pNVIC_ISER = (uint32_t *) NVIC_ISER_ADDR;
	uint32_t *pEXTI_IMR	= (uint32_t *) EXTI_IMR_ADDR;
	uint32_t *pEXTI_RTSR = (uint32_t *) EXTI_RTSR_ADDR;
	uint32_t *pSYSCFG_EXTI_CR_ADDR = (uint32_t *) SYSCFG_EXTI_CR_ADDR;


	// 1. Configuring the GPIO port settings for input button (GPIO Port D, Pin 11)

	*pAHB1ENR |= (1 << GPIO_PORT_NUM);  // Enabling the peripheral clock for GPIOD

	*pGPIO_MODER &= ~(0x03 << 2*GPIO_PIN_NUM_INPUT); // Clearing GPIO Mode Bits
	*pGPIO_MODER |= (GPIO_INPUT_PIN_MODE << 2*GPIO_PIN_NUM_INPUT);  // Setting the GPIO Mode as Input


	//2. Configuring the GPIO port settings for output LED (GPIO Port D, Pin 12)

	*pGPIO_MODER &= ~(0x03 << 2*GPIO_PIN_NUM_OUTPUT); // Clearing GPIO Mode Bits
	*pGPIO_MODER |= (GPIO_OUTPUT_PIN_MODE << 2*GPIO_PIN_NUM_OUTPUT);     // Setting the GPIO Mode as Output


	// 3. Configuring the EXTI Controller (External Interrupt Controller)

	*pEXTI_IMR |= (1 << EXTI_INTERRUPT_PIN_NUM);  // Setting the Interrupt Mask Register
	*pEXTI_RTSR |= (1 << EXTI_INTERRUPT_PIN_NUM); // Setting the Rising Trigger Set Register

	*pAPB2ENR |= (1 << 14);		// Enabling the clock for the System Configuration Block
	*pSYSCFG_EXTI_CR_ADDR &= ~(0xF000);    // Enabling GPIOD Port 11 input on EXTI11 line
	*pSYSCFG_EXTI_CR_ADDR |= (0x3 << 12);

	// 4. Configuring the NVIC Registers

	*pNVIC_ISER |= (1 << (BUTTON_IRQ_NO % 32)); // Enabling the interrupt


	for(;;)
	{


	}

}
