/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define AHB1_ENR_ADDR					(0x40023800UL + 0x30UL)
#define GPIO_MODER_ADDR					0x40020C00UL
#define GPIO_ODR_ADDR					0x40020C14UL
#define GPIO_PORT						3
#define GPIO_PIN_NUM					11                           // External LED is connected here
#define SLEEP_COUNT						500000

void delay(void)
{
	uint32_t j;
	for(j=0;j<SLEEP_COUNT;j++);
}

int main(void)
{
	uint32_t *pAHB1ENR = (uint32_t *) AHB1_ENR_ADDR;
	uint32_t *pGPIO_MODER = (uint32_t *) GPIO_MODER_ADDR;
    uint32_t *pGPIO_ODR = (uint32_t *) GPIO_ODR_ADDR;

	//1. Enable peripheral clock for GPIOD peripheral by writing to AHB1ENR

	*pAHB1ENR |= (1 << GPIO_PORT);

	//2. Set of the mode of GPIOD, Pin 12 as output by writing to GPIOD_MODER

    *pGPIO_MODER |= (1 << 2*GPIO_PIN_NUM);

	for(;;)
	{
		//3. Make LED COnnected Pin of GPIOD as HIGH by writing to GPIOD_ODR
		*pGPIO_ODR |= (1 << GPIO_PIN_NUM);
		delay();

		//4. Make LED Connected Pin of GPIOD as LOW by writing to GPIOD_ODR
		*pGPIO_ODR &= ~(1 << GPIO_PIN_NUM);
		delay();
	}
}
