/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	__asm volatile ("LDR R0, =0xabcdcdef");
	__asm volatile ("MOV R1, #0x1");
	__asm volatile ("ADDS R2, R0, R1");
	__asm volatile ("MRS R3, CONTROL");
	__asm volatile ("ORR R4, R0, #0x1");
	__asm volatile ("AND R5, R0, #0x1");
	__asm volatile ("BIC R6, R0, #0x1");
	__asm volatile ("BIC R12, R0, R1");
	__asm volatile ("LDR R8, =0x20001000");
	__asm volatile ("STR R0, [R8]");
	__asm volatile ("LDRB R9, [R8]");

    /* Loop forever */
	for(;;);
}
